### ISSUE TITLE
Key error when writing geomopt trajectory

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/janus-core#261]
We get a `KeyError` when trying to write a geomopt trajectory if the dispersion is set to True for the MACE calculator, which I think must be related to the use of the `SumCalculator`.:

```
janus geomopt --struct tests/data/NaCl.cif --traj NaCl-traj.extxyz --calc-kwargs "{'dispersion': True}"
[codecarbon INFO @ 10:39:15] offline tracker init
Using Materials Project MACE for MACECalculator with /home/ek/.cache/mace/46jrkm3v
Using float64 for MACECalculator, which is slower but more accurate. Recommended for geometry optimization.
Using TorchDFTD3Calculator for D3 dispersion corrections (see https://github.com/pfnet-research/torch-dftd)
       Step     Time          Energy          fmax
LBFGS:    0 10:39:19      -28.745522        0.000000
Traceback (most recent call last):

  File "/home/ek/PSDI/venv_janus_11_new/bin/janus", line 6, in <module>
    sys.exit(app())
             ^^^^^

  File "/home/ek/PSDI/janus-core/janus_core/cli/geomopt.py", line 289, in geomopt
    optimizer.run()

  File "/home/ek/PSDI/janus-core/janus_core/calculations/geom_opt.py", line 291, in run
    output_structs(

  File "/home/ek/PSDI/janus-core/janus_core/helpers/utils.py", line 300, in output_structs
    results_to_info(

  File "/home/ek/PSDI/janus-core/janus_core/helpers/utils.py", line 244, in results_to_info
    arch = struct.calc.parameters["arch"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^

KeyError: 'arch'
```

**Comment by alinelena** [comment]
had it yesterday too did not dig into it too much, we will need also a test to catch it
